# Default values for loadtest-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


master:
  replicaCount: 1
  image:
    repository: maximenoel8/locust
    tag: latest
    pullPolicy: IfNotPresent

slave:
  replicaCount: 4
  image:
    repository: maximenoel8/locust
    tag: latest
    pullPolicy: IfNotPresent

targetHost: http://wordpress.example.com:30880

namespace: locust

hostAliases:
  ip: 10.84.72.194
  host: wordpress.example.com

hostName:
  name: locust.example.com
  secretName: locust-tls