apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-slave
  labels:
    app: {{ template "fullname" . }}
    component: locust-slave
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.slave.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
      component: locust-slave
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: locust-slave
        name: {{ template "fullname" . }}-locust-slave
    spec:
      hostAliases:
          - ip: {{ .Values.hostAliases.ip}}
            hostnames:
              - "{{ .Values.hostAliases.host }}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.slave.image.repository }}:{{ .Values.slave.image.tag }}"
          imagePullPolicy: {{ .Values.slave.image.pullPolicy }}
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: {{ .Release.Name }}-master
            - name: TARGET_HOST
              value: "{{ .Values.targetHost }}"
